abstract: Tag URI Scheme (RFC 4151)
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: URI-tag
no_index: 
  directory: 
    - inc
    - t
version: 0.01
